version: '3.8'

services:
  postgres-db-proposta:
    image: postgres:15
    container_name: postgres-db-proposta
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PropostaDb
    volumes:
      - postgres_proposta_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d PropostaDb"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

  postgres-db-contratacao:
    image: postgres:15
    container_name: postgres-db-contratacao
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ContratacaoDb
    volumes:
      - postgres_contratacao_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ContratacaoDb -h localhost -p 5432"]
      interval: 20s
      timeout: 5s
      retries: 5

  proposta-service:
    build:
      context: ./Proposta.Service
      dockerfile: Dockerfile
    container_name: proposta-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db-proposta;Port=5432;Database=PropostaDb;Username=user;Password=password
      - ASPNETCORE_URLS=http://+:8080
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    depends_on:
      postgres-db-proposta:
        condition: service_healthy
    ports:
      - "5000:8080"
    restart: unless-stopped

  contratacao-service:
    build:
      context: ./Contratacao.Service
      dockerfile: Dockerfile
    container_name: contratacao-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db-contratacao;Port=5432;Database=ContratacaoDb;Username=user;Password=password
      - Services__PropostaService__BaseUrl=http://proposta-service:8080/propostas
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft=Information
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - Logging__LogLevel__System=Information
    depends_on:
      postgres-db-contratacao:
        condition: service_healthy
      proposta-service:
        condition: service_started
    ports:
      - "5001:8080"
    stdin_open: true
    tty: true

volumes:
  postgres_proposta_data:
  postgres_contratacao_data:
